version: "3.9"
services:
  db:
    image: postgres:16
    container_name: kanban_postgres
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kanban"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data: